package main

func generateBaseHtml() string {
	return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A webapp generated by Vial">
    <title>{% block title %}My Flask App{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>

    <header>
        <h1>Welcome</h1>
    </header>

    <main>
        {% block content %}
        <p>This is a site generated using Vial.</p>
        {% endblock %}
    </main>

    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>`
}

func generateIndexHtml() string {
	return `{%extends base.html%}

{%block title%}Home{%endblock%}

{%block content%}
{%endblock%}`
}

func generateMainPy() string {
	return `from website import create_app

app = create_app()


if __name__ == "__main__":
    app.run()
`
}

func generateInitPy() string {
	return `from flask import Flask 

def create_app():
    app = Flask(__name__)

    from .routes.views import views
    from .routes.auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")
    return app
`
}

func generateViewsPy() string {
	return `from flask import Blueprint, request, render_template

views = Blueprint("views", __name__)

@views.route("/")
def home():
    return render_template("index.html")
`
}

func generateAuthPy() string {
	return `
from flask import Blueprint, request, render_template

auth = Blueprint("auth", __name__)

`
}
